# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text2img.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'text2img.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etext2img.proto\"\x18\n\x06Prompt\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"&\n\nPromptList\x12\x18\n\x07prompts\x18\x01 \x03(\x0b\x32\x07.Prompt\"9\n\rImageResponse\x12\x14\n\x0csuccess_code\x18\x01 \x01(\t\x12\x12\n\nimage_path\x18\x02 \x01(\t\"3\n\x11ImageResponseList\x12\x1e\n\x06images\x18\x01 \x03(\x0b\x32\x0e.ImageResponse2D\n\x0fText2ImgService\x12\x31\n\x0eGenerateImages\x12\x0b.PromptList\x1a\x12.ImageResponseListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text2img_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMPT']._serialized_start=18
  _globals['_PROMPT']._serialized_end=42
  _globals['_PROMPTLIST']._serialized_start=44
  _globals['_PROMPTLIST']._serialized_end=82
  _globals['_IMAGERESPONSE']._serialized_start=84
  _globals['_IMAGERESPONSE']._serialized_end=141
  _globals['_IMAGERESPONSELIST']._serialized_start=143
  _globals['_IMAGERESPONSELIST']._serialized_end=194
  _globals['_TEXT2IMGSERVICE']._serialized_start=196
  _globals['_TEXT2IMGSERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
